server:
  port: 8085

# 评论展示需拉取用户昵称/头像；有 Nacos 时用 http://user-service，本地直连可配 http://localhost:8081
app:
  user-service-url: http://localhost:8081

spring:
  application:
    name: interaction-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        ip: 127.0.0.1
        port: ${server.port}
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
